# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-24 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_names_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='names_id',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='names_id',
        ),
        migrations.AddField(
            model_name='names',
            name='emails',
            field=models.ManyToManyField(to='phonebook.email'),
        ),
        migrations.AddField(
            model_name='names',
            name='phones',
            field=models.ManyToManyField(to='phonebook.phone'),
        ),
    ]
