# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-24 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_auto_20180324_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='names',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='names',
            name='phones',
        ),
        migrations.AddField(
            model_name='email',
            name='names_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='phonebook.names'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='names_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='phonebook.names'),
            preserve_default=False,
        ),
    ]
